### ISSUE TITLE
Always black

### ISSUE THREAD

**Issue by drakonkat** [saurabhgour/react-native-progress-circle-without-library#1]
Hi, i have imported the component, passed only the percentage but the circle result always black.

<CircularProgress
              percent={60}
            />

**Comment by drakonkat** [comment]
This is my simple code

```
<CircularProgress
              percent={60}
            />
```

**Comment by lutakyn** [comment]
I have the same issue as well. Even when I change the colors of the parameters,it doesn't work

**Comment by kiroukou** [comment]
I do have the same issue on Android only..
Anyone found a solution yet?

**Comment by Hafid00** [comment]
Any solution?

**Comment by ghost** [comment]
PR: #2

**Comment by saurabhgour** [comment]
Oh, sorry guys. Haven't looked at my github page in quite some time. Did'nt think anyone would end up using this. Would try to look into the issue.

**Comment by saurabhgour** [comment]
I have updated the README.MD with the blogs explaining the detailed library implementation.

**Comment by saurabhgour** [comment]
I've merged a PR for this, haven't tested it, please let me know if issue still exists
